"""Generate Tests/Fixtures/B0Objectives.h from the B0 native log.

Usage:
    python3 gen_objectives_fixture.py <native log> <out header>

Input:  the B0 probe's native log (evidence corpus `%TEMP%\\glacier-m0\\hitmen\\b0-run1\\relay-20261007-014849-93996.log`,
        2026-10-07, Paris, game 3.280.0.0). Read only; never modified or regenerated by this script.
Output: the C++ header holding every ObjectiveCompleted event the engine's JSON writer logged (one in B0), exactly as
        logged, including the "Name-first" envelope variant with the top-level XboxGameMode/XboxDifficulty members.
        To verify a committed header, generate into a temporary path and compare byte for byte.

Identifier-removal rules (the only edits to the logged text): the `"UserId":"..."` and `"SessionId":"..."` members
(the user's account id and the platform session id) are removed textually with their leading comma; every other byte,
including ContractSessionId, ContractId, Origin, Timestamp and the event Id, is kept verbatim. The script asserts that
the Value object is unchanged by the removal.
"""
import json, re, sys

log, out = sys.argv[1], sys.argv[2]
rows = []
for line in open(log, encoding="utf-8", errors="replace"):
    m = re.search(r"sent #(\d+) \(index (\d+), frame (\d+)\): (\{.*\})\s*$", line)
    if not m:
        continue
    text = m.group(4)
    e = json.loads(text)
    if e.get("Name") != "ObjectiveCompleted":
        continue
    stripped = re.sub(r',"UserId":"[^"]*"', "", text)
    stripped = re.sub(r',"SessionId":"[^"]*"', "", stripped)
    assert json.loads(stripped)["Value"] == e["Value"]
    rows.append((int(m.group(1)), int(m.group(2)), int(m.group(3)), e, stripped))

assert len(rows) == 1, len(rows)

with open(out, "w", encoding="utf-8", newline="\n") as f:
    f.write("#pragma once\n\n")
    f.write("// The ObjectiveCompleted event(s) the game emitted in the B0 probe (2026-10-07, Paris, game 3.280.0.0): one, 13 ms\n")
    f.write("// after the Kill of the target Viktor Novikov, verbatim from the native log except that the user and platform\n")
    f.write("// session identifiers are removed. The envelope is the \"Name-first\" variant (top-level XboxGameMode/XboxDifficulty,\n")
    f.write("// Timestamp after Value) that B0 also showed on ContractStart/ContractFailed/Spotted/Witnesses (glacier-relay M2\n")
    f.write("// design, section 42.1). Value: {Id, Type: \"kill\", Category: \"primary\", ExcludeFromScoring: false}; the engine field\n")
    f.write("// types are unknown. Generated from the B0 corpus; do not edit by hand.\n\n")
    f.write("#include <cstddef>\n\nnamespace B0Fixtures\n{\n")
    f.write("    struct RawObjectiveEvent { int probe_sequence; int event_index; int frame; const char* json; };\n\n")
    f.write("    inline const RawObjectiveEvent k_Objectives[] = {\n")
    for seq, idx, frame, e, text in rows:
        f.write(f'        {{{seq}, {idx}, {frame}, R"json({text})json"}},\n')
    f.write("    };\n\n")
    f.write("    inline constexpr size_t k_ObjectiveCount = sizeof(k_Objectives) / sizeof(k_Objectives[0]);\n\n")
    e = rows[0][3]
    f.write(f"    inline constexpr size_t k_ObjectiveNovikovKill = 0; // Timestamp {e['Timestamp']}, after Kill index {rows[0][1] - 1}\n")
    f.write(f'    inline constexpr const char* k_ObjectiveNovikovId = "{e["Value"]["Id"]}"; // opaque; compared with nothing\n')
    f.write("}\n")
print("wrote", out, "rows", len(rows))
for seq, idx, frame, e, text in rows:
    print(seq, idx, e["Timestamp"], e["Value"])
