"""Generate Tests/Fixtures/B0Items.h from the B0 native log.

Usage:
    python3 gen_items_fixture.py <native log> <out header>

Input:  the B0 probe's native log (evidence corpus `%TEMP%\\glacier-m0\\hitmen\\b0-run1\\relay-20261007-014849-93996.log`,
        2026-10-07, Paris, game 3.280.0.0). Read only; never modified or regenerated by this script.
Output: the C++ header holding the 24 ItemPickedUp / ItemThrown / ItemRemovedFromInventory events (12 / 6 / 6)
        exactly as the engine's JSON writer logged them, plus role indices and the seven definition ids.
        To verify a committed header, generate into a temporary path and compare byte for byte.

Identifier-removal rules (the only edits to the logged text): the `"UserId":"..."` and `"SessionId":"..."` members
(the user's account id and the platform session id) are removed textually with their leading comma; every other
byte of each event, including ContractSessionId, ContractId, Origin and the event Id, is kept verbatim. The script
asserts that the Value object is unchanged by the removal.
"""
import json, re, sys

log, out = sys.argv[1], sys.argv[2]
NAMES = ("ItemPickedUp", "ItemThrown", "ItemRemovedFromInventory")
rows = []
for line in open(log, encoding="utf-8", errors="replace"):
    m = re.search(r"sent #(\d+) \(index (\d+), frame (\d+)\): (\{.*\})\s*$", line)
    if not m:
        continue
    text = m.group(4)
    e = json.loads(text)
    if e.get("Name") not in NAMES:
        continue
    # Strip the two identifiers textually so everything else stays byte-for-byte as logged.
    stripped = re.sub(r',"UserId":"[^"]*"', "", text)
    stripped = re.sub(r',"SessionId":"[^"]*"', "", stripped)
    assert json.loads(stripped)["Value"] == e["Value"]
    rows.append((int(m.group(1)), int(m.group(2)), int(m.group(3)), e["Name"], e["Value"], stripped))

assert len(rows) == 24, len(rows)
counts = {n: sum(1 for r in rows if r[3] == n) for n in NAMES}
assert counts == {"ItemPickedUp": 12, "ItemThrown": 6, "ItemRemovedFromInventory": 6}, counts
defs = []
for r in rows:
    rid = r[4]["RepositoryId"]
    if rid not in defs:
        defs.append(rid)
assert len(defs) == 7, defs

with open(out, "w", encoding="utf-8", newline="\n") as f:
    f.write("#pragma once\n\n")
    f.write("// The 12 ItemPickedUp, 6 ItemRemovedFromInventory and 6 ItemThrown events the game emitted in the B0 probe\n")
    f.write("// (2026-10-07, Paris, game 3.280.0.0), verbatim from the native log except that the user and platform session\n")
    f.write("// identifiers are removed. Every Value is an object with the same seven keys (glacier-relay M2 design,\n")
    f.write("// section 38.1): InstanceId (empty in 24/24), ItemType, ItemName, RepositoryId, OnlineTraits, Category (null in\n")
    f.write("// 24/24), ActionRewardType (\"AR_None\" in 24/24). Generated from the B0 corpus; do not edit by hand.\n\n")
    f.write("#include <cstddef>\n\nnamespace B0Fixtures\n{\n")
    f.write("    struct RawItemEvent { int probe_sequence; int event_index; int frame; const char* json; };\n\n")
    f.write("    inline const RawItemEvent k_Items[] = {\n")
    for seq, idx, frame, name, value, text in rows:
        f.write(f'        {{{seq}, {idx}, {frame}, R"json({text})json"}},\n')
    f.write("    };\n\n")
    f.write("    inline constexpr size_t k_ItemCount = sizeof(k_Items) / sizeof(k_Items[0]);\n\n")
    f.write("    // Indices into k_Items, by role in the B0 session (order of emission).\n")
    names = {
        0: "k_ItemWrenchPickup1", 1: "k_ItemWrenchRemoved1", 2: "k_ItemWrenchThrown1", 3: "k_ItemWrenchPickup2",
        4: "k_ItemWrenchRemoved2", 5: "k_ItemWrenchThrown2", 6: "k_ItemWrenchPickup3", 7: "k_ItemCrowbarPickup1",
        8: "k_ItemCrowbarRemoved1", 9: "k_ItemCrowbarThrown1", 10: "k_ItemCrowbarPickup2", 11: "k_ItemCrowbarPickup3",
        12: "k_ItemRatPoisonPickup", 13: "k_ItemLeadPipePickup", 14: "k_ItemKnifePickup1", 15: "k_ItemCleaverPickup",
        16: "k_ItemLeadPipeRemoved", 17: "k_ItemLeadPipeThrown", 18: "k_ItemKnifeRemoved", 19: "k_ItemKnifeThrown",
        20: "k_ItemKnifePickup2", 21: "k_ItemPropanePickup", 22: "k_ItemPropaneRemoved", 23: "k_ItemPropaneThrown",
    }
    for i, (seq, idx, frame, name, value, text) in enumerate(rows):
        f.write(f"    inline constexpr size_t {names[i]:<24} = {i:2}; // {name} {value['ItemName']} ({value['RepositoryId'][:8]}) Timestamp {json.loads(text)['Timestamp']}\n")
    f.write("\n    // The seven item definition ids, in first-seen order.\n")
    for i, d in enumerate(defs):
        nm = next(r[4]["ItemName"] for r in rows if r[4]["RepositoryId"] == d)
        f.write(f'    inline constexpr const char* k_ItemDefinition{i + 1} = "{d}"; // {nm}\n')
    f.write("}\n")
print("wrote", out, "rows", len(rows), "definitions", len(defs))
for r in rows:
    print(r[0], r[1], r[3], r[4]["ItemName"], r[4]["RepositoryId"][:8], json.loads(r[5])["Timestamp"])
